services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vaultpay
      POSTGRES_USER: vaultuser
      POSTGRES_PASSWORD: vaultpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
